### ISSUE TITLE
Ruby kanban board setup

### ISSUE THREAD

**Issue by cosywasswa** [cosywasswa/catalogue-of-my-things#42]
Here is a link to our project
https://github.com/cosywasswa/catalogue-of-my-things/projects/1
We are a group of 3 members.
Team member #1 - @Kgomotso196
Team member #2 - @aradradev 
Team member #3 - @cosywasswa

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @cosywasswa, @aradradev and @Kgomotso196,

Good job so far!
✔️ Kanban columns are complete
✔️ Tasks are well assigned
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Kindly add the actual description for the tasks instead of just adding a rather generic "Description to be added". All tasks should have meaningful descriptions. Kindly do this for all tasks where you have this sort of description.

  ![image](https://github.com/cosywasswa/catalogue-of-my-things/assets/36542986/1e9826b5-7fb0-430a-9dc0-4965391e9645)

- [ ] Team member 1, @Kgomotso196 is handling Book and Label class implementations but he has a task from the MusicAlbum and Genre tasks which is not his. This task belongs to @aradradev - and he does not have it. Kindly fix that.

  Kindly also ensure the task title and description are related. You title your task for test activity but it has the startup task description.

  ![image](https://github.com/cosywasswa/catalogue-of-my-things/assets/36542986/93977fee-b4ac-45ca-b0ed-2420f18e11a0)

- [ ] 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by DammyShittu** [comment]
Hi @cosywasswa, @aradradev and @Kgomotso196,

## APPROVED 🟢

## Highlights
✔️ Descriptive tasks

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
